function markCurrent(status){let ses=visibleSessions().find(x=>x.id===S.selected);if(!ses)return;let r=roster(ses),idx=S.rollIndex,st=r[idx];if(!st)return;let [k,rec]=sessionRecord(ses),previous=rec[st.id];S.undo={sessionId:ses.id,sessionKey:k,studentId:st.id,studentIndex:idx,previousStatus:previous,newStatus:status};rec[st.id]=status;S.attendance[k]=rec;playMarkSound(status);if(S.rollIndex<r.length-1)S.rollIndex++;else S.rollIndex=r.length;renderRoll();queueSave(k,rec);audit('mark',ses,st.id,previous||null,status,{student_name:st.name})}

function undoLastMark(){
  const u=S.undo;if(!u)return;
  const ses=visibleSessions().find(x=>x.id===u.sessionId);if(!ses||u.sessionKey!==key(ses)){S.undo=null;renderRoll();return}
  let rec={...(S.attendance[u.sessionKey]||{})};
  if(u.previousStatus)rec[u.studentId]=u.previousStatus;else delete rec[u.studentId];
  rec.__meta={...(rec.__meta||{}),course:ses.course,type:ses.type,venue:ses.venue||'',date:iso(),takenBy:S.staff.full_name,takenByRole:S.staff.role,lecturer:ses.lecturer||rec.__meta?.lecturer||S.staff.full_name,lectureNumber:ses.lectureNumber||rec.__meta?.lectureNumber||1,baseSessionId:ses.baseSessionId||rec.__meta?.baseSessionId||ses.id,savedAt:new Date().toISOString()};
  S.attendance[u.sessionKey]=rec;S.rollIndex=u.studentIndex;S.undo=null;renderRoll();queueSave(u.sessionKey,rec);audit('undo',ses,u.studentId,u.newStatus,u.previousStatus||null,{});
}
function canUndoHere(){return !!(S.undo&&S.undo.sessionId===S.selected&&S.undo.sessionKey===key(visibleSessions().find(x=>x.id===S.selected)||{}))}
async function restartCurrentSession(){if(S.staff?.role!=='admin')return;let ses=visibleSessions().find(x=>x.id===S.selected);if(!ses)return;let k=key(ses),r=roster(ses),rec=S.attendance[k]||{},marked=r.filter(st=>rec[st.id]).length;if(!marked){S.rollIndex=0;renderRoll();return}if(!confirm(`Restart ${ses.course} ${ses.type} attendance for today? This will clear ${marked} saved marks for this session only.`))return;try{await saveChain;await req('/rest/v1/attendance_sessions?session_key=eq.'+encodeURIComponent(k),{method:'DELETE'});delete S.attendance[k];S.rollIndex=0;S.undo=null;renderRoll();audit('restart',ses,null,null,null,{cleared_marks:marked})}catch(e){alert('Could not restart this session: '+e.message)}}

async function remainingAbsent(){let ses=visibleSessions().find(x=>x.id===S.selected);if(!ses)return;let k=key(ses),rec={...(S.attendance[k]||{})};roster(ses).forEach(st=>{if(!rec[st.id])rec[st.id]='absent'});rec.__meta={course:ses.course,type:ses.type,venue:ses.venue||'',date:iso(),takenBy:S.staff.full_name,takenByRole:S.staff.role,lecturer:ses.lecturer||S.staff.full_name,lectureNumber:ses.lectureNumber||1,baseSessionId:ses.baseSessionId||ses.id,cohort:'',savedAt:new Date().toISOString()};let newly=roster(ses).filter(st=>!(S.attendance[k]||{})[st.id]).length;S.attendance[k]=rec;renderRoll();await req('/rest/v1/attendance_sessions?on_conflict=session_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({session_key:k,data:rec,updated_at:new Date().toISOString()})});audit('bulk_absent',ses,null,null,'absent',{count:newly})}
function calc(){let students=S.state.students||[],keys=Object.keys(S.attendance),per=students.map(st=>{let n=0,a=0,by={};keys.forEach(k=>{let rec=S.attendance[k],v=rec?.[st.id];if(!v)return;let c=rec.__meta?.course||'Unknown',w=lectureWeight(rec);by[c]??={n:0,a:0};n+=w;by[c].n+=w;if(v==='present'||v==='late'){a+=w;by[c].a+=w}});let rates=Object.fromEntries(Object.entries(by).map(([c,o])=>[c,Math.round(o.a/o.n*100)]));return{...st,n,a,rate:n?Math.round(a/n*100):null,rates}});let vals=per.filter(x=>x.rate!=null),avg=vals.length?Math.round(vals.reduce((s,x)=>s+x.rate,0)/vals.length):null;return{per,avg}}

function bandForRate(rate){if(rate==null)return{cls:'dgrey',pct:'pctgrey',label:'No data',rank:3};if(rate<75)return{cls:'dred',pct:'pctred',label:'Red',rank:0};if(rate<85)return{cls:'damber',pct:'pctamber',label:'Amber',rank:1};return{cls:'dgreen',pct:'pctgreen',label:'Green',rank:2}}