function reportData(){
  let students=S.state.students||[],{per,avg}=calc(),keys=Object.keys(S.attendance).sort(),courseNames=[...new Set(keys.map(k=>S.attendance[k].__meta?.course).filter(Boolean))],threshold=S.state.settings?.threshold||75;
  let ov=[['Nile University FBCS Roll Call'],['Generated',new Date().toLocaleString()],['Students',students.length],['Registers',keys.length],['Average attendance',avg==null?'':avg+'%'],['Threshold',threshold+'%']];
  let list=[['ID','Name'],...students.map(x=>[x.id,x.name])];
  let matrix=[['ID','Name',...keys.map(k=>{let m=S.attendance[k].__meta||{};return`${m.date||''} ${m.course||''} ${m.type||''}${m.outOfTimetable?' [OUT OF TIMETABLE]':''}`})],...students.map(st=>[st.id,st.name,...keys.map(k=>markLabel(S.attendance[k][st.id]))])];
  let rates=[['ID','Name','Attended','Counted','Rate %',...courseNames],...per.map(x=>[x.id,x.name,x.a,x.n,x.rate??'',...courseNames.map(c=>x.rates[c]??'')])];
  let risk=[['ID','Name','Rate %'],...per.filter(x=>x.rate!=null&&x.rate<threshold).map(x=>[x.id,x.name,x.rate])];
  let slog=[['Session key','Date','Course','Type','Timetable status','Reason','Venue','Taken by','Marked','Present','Late','Absent'],...keys.map(k=>{let r=S.attendance[k],m=r.__meta||{},vals=Object.entries(r).filter(([x])=>x!=='__meta').map(([,v])=>v);return[k,m.date||'',m.course||'',m.type||'',m.outOfTimetable?'Out of official timetable':'Official timetable',m.reason||'',m.venue||'',m.takenBy||m.lecturer||'',vals.length,vals.filter(x=>x==='present').length,vals.filter(x=>x==='late').length,vals.filter(x=>x==='absent').length]})];
  let det=[['Date','Course','Type','Timetable status','Reason','Venue','Taken by','Student ID','Student name','Status','Attended']];
  keys.forEach(k=>{let r=S.attendance[k],m=r.__meta||{};Object.entries(r).forEach(([id,status])=>{if(id==='__meta')return;let st=students.find(x=>x.id===id);det.push([m.date||'',m.course||'',m.type||'',m.outOfTimetable?'Out of official timetable':'Official timetable',m.reason||'',m.venue||'',m.takenBy||m.lecturer||'',id,st?.name||'',markLabel(status),(status==='present'||status==='late')?'Yes':'No'])})});
  let csum=[['Course','Registers','Average %']];courseNames.forEach(c=>{let ps=per.map(x=>x.rates[c]).filter(x=>x!=null);csum.push([c,keys.filter(k=>S.attendance[k].__meta?.course===c).length,ps.length?Math.round(ps.reduce((a,b)=>a+b,0)/ps.length):''])});
  let extras=[['Date','Course','Time','Type','Venue','Added by','Reason','Label'],...(S.extraSessions||[]).map(x=>[x.date,courseLabel(x.course),`${x.start}-${x.end}`,x.type,x.venue||'',x.createdBy||'',x.reason||'',x.label||'OUT OF OFFICIAL TIMETABLE CLASS'])];
  return{Overview:ov,Students:list,'Attendance Matrix':matrix,'Student Rates':rates,'Course Summary':csum,'At Risk':risk,'Session Log':slog,'Detailed Marks':det,'Out-of-Timetable Classes':extras}
}
async function downloadAllReports(btn){let old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Preparing Excel…'}try{let r=await fetch(URL+'/functions/v1/export-attendance-xlsx',{method:'GET',headers:{apikey:KEY,Authorization:`Bearer ${S.session?.access_token||''}`}});if(!r.ok){let t=await r.text();throw Error(t||'Could not create Excel report')}let blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Nile_FBCS_RollCall_All_Reports_${iso()}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){alert('Excel download failed: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
async function dl(sheet,btn){let old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Preparing…'}try{let r=await fetch(URL+'/functions/v1/export-attendance-xlsx?sheet='+encodeURIComponent(sheet),{method:'GET',headers:{apikey:KEY,Authorization:`Bearer ${S.session?.access_token||''}`}});if(!r.ok){let t=await r.text();throw Error(t||'Could not create Excel report')}let blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Nile_FBCS_RollCall_${sheet.replace(/ /g,'_')}_${iso()}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){alert('Excel download failed: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
function renderSummary(){let v=$('#view'),{per}=calc(),th=S.state.settings?.threshold||75,risk=per.filter(x=>x.rate!=null&&x.rate<th);let names=Object.keys(reportData());v.innerHTML=`<div class="card"><b>Report downloads</b><div class="muted" style="margin-top:4px">All existing report downloads remain available. The combined workbook is generated on the server.</div><button class="btn green" style="margin-top:12px" onclick="downloadAllReports(this)">Download all Excel reports</button><div class="grid" style="margin-top:10px">${names.filter(x=>x!=='Overview').map(n=>`<button class="btn light" onclick="dl('${n}',this)">${n}</button>`).join('')}<button class="btn light" onclick="dl('Pathology Attendance',this)">Combined Pathology</button><button class="btn light" onclick="dl('Pharmacology & Therapeutics',this)">Pharmacology & Therapeutics</button></div></div>${renderPathologyAttendance()}<div class="card"><b>At risk below ${th}%</b><div style="margin-top:8px">${risk.length?risk.map(x=>`<div class="row"><span class="grow">${esc(x.name)}</span><b style="color:#e11d48">${x.rate}%</b></div>`).join(''):'<div class="muted">No students below threshold yet.</div>'}</div></div>`}